version: "2.4"
services:
  docker_workstation_computer:
    extends:
      file: docker-compose.yml
      service: docker_workstation_computer
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
